import { PresetDilemma } from '../types';

export const PRESET_DILEMMAS: PresetDilemma[] = [
  {
    id: 'career-1',
    title: '要不要裸辞去大理/旅居换个生活节奏？',
    category: 'career',
    categoryLabel: '职场与发展',
    optionA: '裸辞出发，换个活法',
    optionB: '稳住现状，攒钱再说',
    tag: '打工人出逃',
  },
  {
    id: 'career-2',
    title: '大厂高薪内卷 vs 国企/稳定慢节奏？',
    category: 'career',
    categoryLabel: '职场与发展',
    optionA: '冲大厂高薪，拼三年',
    optionB: '选稳定慢节奏，保健康',
    tag: '人生道路抉择',
  },
  {
    id: 'emotion-1',
    title: '要不要主动找那个已经断联一周的TA发微信？',
    category: 'emotion',
    categoryLabel: '情感与社交',
    optionA: '主动破冰，不留遗憾',
    optionB: '按兵不动，保持体面',
    tag: '感情拉扯',
  },
  {
    id: 'shopping-1',
    title: '这件心动了整整半个月的千元大件，到底买不买？',
    category: 'shopping',
    categoryLabel: '消费与拔草',
    optionA: '立刻下单，取悦自己',
    optionB: '果断拔草，守住钱包',
    tag: '冲动消费',
  },
  {
    id: 'life-1',
    title: '今晚吃麻辣火锅犒劳自己 vs 坚持轻食控卡？',
    category: 'life',
    categoryLabel: '生活与健康',
    optionA: '火锅走起，快乐无价',
    optionB: '轻食自律，明天更轻',
    tag: '深夜吃货纠结',
  },
  {
    id: 'tech-1',
    title: '业余时间要不要从零开始做一个自己的AI独立产品？',
    category: 'tech',
    categoryLabel: '个人成长',
    optionA: '今晚就开工，万一爆了呢',
    optionB: '先看剧打游戏放松，太累了',
    tag: '独立开发者',
  },
  {
    id: 'emotion-2',
    title: '周末朋友聚会要不要找借口推掉，一个人宅家？',
    category: 'emotion',
    categoryLabel: '情感与社交',
    optionA: '社恐回血，安心宅家',
    optionB: '赴约社交，维持感情',
    tag: '电量耗尽',
  },
];
